name: Continuous integration
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-20.04
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - uses: coursier/cache-action@v6.3
      - run: docker run -d -p 8080:8080 julienrf/endpoints4s-stubserver:1.0.1
      - name: Tests
        run: sbt "coverage; +test; coverageReport; coverageAggregate"
      - run: bash <(curl -s https://codecov.io/bash)
      - name: Version Policy Check
        run: sbt versionPolicyCheck
      - name: Code formatting
        run: sbt scalafmtCheck
