name: Release
on:
  push:
    tags: ["v*"]

jobs:

  publish:
    runs-on: ubuntu-20.04
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - uses: coursier/cache-action@v6.3
      - run: sbt versionCheck
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - run: sbt ci-release
      - name: Generate site
        run: sbt makeSite
      - uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages
          folder: documentation/target/site
